datavault_extension:
  outputs:
    dev:
      account: ''
      database: ''
      password: ''
      role: accountadmin
      schema: <schema>
      threads: 6
      type: snowflake
      user: ''
      warehouse: compute_wh
  target: dev