datavault_extension:
  outputs:
    dev:
      account: {{ env_var(''DWH_SNOWFLAKE_ACCOUNT'') }}
      database: '{{ env_var(''DWH_DATABASE'',''DWS'') }}'
      password: '{{ env_var(''DWH_PASSWORD'') }}'
      role: accountadmin
      schema: <schema>
      threads: 6
      type: snowflake
      user: '{{ env_var(''DWH_USER'') }}'
      warehouse: compute_wh
  target: dev